Repository silverstripe/silverstripe-userforms, pull requests merged in 2018-08, with the labels that each got.

#798 FIX Remove divider line and add margin underneath Submissions GridField
  code/Model/Submission/SubmittedForm.php
Labels: affects/v4, change/patch, type/UX

#736 Test against PgSQL also
  .travis.yml
  code/Model/EditableFormField.php
  code/Model/Recipient/EmailRecipient.php
  code/Model/Submission/SubmittedForm.php
Labels: affects/v4, effort/easy, impact/low, type/enhancement

#799 FIX Submitted form field values are no longer double escaped in the CMS
  code/Model/Submission/SubmittedFormField.php
Labels: affects/v4, change/patch
