Repository silverstripe/silverstripe-userforms, pull requests merged in 2018-03, with the labels that each got.

#728 FIX stop form items double duplicating
  .travis.yml
  code/Model/EditableFormField.php
  code/Model/EditableFormField/EditableMultipleOptionField.php
  code/UserForm.php
  tests/Model/EditableFormFieldTest.php
  tests/Model/UserDefinedFormTest.php
Labels: affects/v4, effort/medium, impact/high, type/bug

#725 Add PHP 7.2 to Travis build matrix
  .travis.yml
Labels: affects/v4

#743 API Remove use of getEscapedTitle() and deprecated for future removal. Use $Title directly instead.
  code/Model/EditableFormField.php
  code/Model/EditableFormField/EditableCheckbox.php
  code/Model/EditableFormField/EditableCheckboxGroupField.php
  code/Model/EditableFormField/EditableCountryDropdownField.php
  code/Model/EditableFormField/EditableDateField.php
  code/Model/EditableFormField/EditableDropdown.php
  code/Model/EditableFormField/EditableEmailField.php
  code/Model/EditableFormField/EditableFieldGroup.php
  code/Model/EditableFormField/EditableFileField.php
  code/Model/EditableFormField/EditableFormHeading.php
  code/Model/EditableFormField/EditableFormStep.php
  code/Model/EditableFormField/EditableMemberListField.php
  code/Model/EditableFormField/EditableNumericField.php
  code/Model/EditableFormField/EditableOption.php
  code/Model/EditableFormField/EditableRadioField.php
  code/Model/EditableFormField/EditableTextField.php
Labels: affects/v4, change/minor

#745 FIX Correctly return the max file size in MB
  code/Model/EditableFormField/EditableFileField.php
Labels: affects/v4, change/patch

#748 FIX Disable versioned GridField extensions - it conflicts with UserFormRecipientItemRequest
  code/Model/Recipient/EmailRecipient.php
Labels: affects/v4, change/patch

#754 FIX Allow editable form fields to have nullable titles rather than fallback to Name
  code/Model/EditableFormField/EditableCheckbox.php
  code/Model/EditableFormField/EditableCheckboxGroupField.php
  code/Model/EditableFormField/EditableCountryDropdownField.php
  code/Model/EditableFormField/EditableDateField.php
  code/Model/EditableFormField/EditableDropdown.php
  code/Model/EditableFormField/EditableEmailField.php
  code/Model/EditableFormField/EditableFileField.php
  code/Model/EditableFormField/EditableFormHeading.php
  code/Model/EditableFormField/EditableMemberListField.php
  code/Model/EditableFormField/EditableNumericField.php
  code/Model/EditableFormField/EditableRadioField.php
  code/Model/EditableFormField/EditableTextField.php
  tests/Control/UserDefinedFormControllerTest.php
  tests/Model/EditableFormField/EditableCheckboxGroupFieldTest.php
  tests/Model/EditableFormField/EditableCheckboxTest.php
  tests/Model/EditableFormField/EditableCountryDropdownFieldTest.php
  tests/Model/EditableFormField/EditableDateFieldTest.php
  tests/Model/EditableFormField/EditableDropdownTest.php
  tests/Model/EditableFormField/EditableEmailFieldTest.php
  tests/Model/EditableFormField/EditableFieldGroupTest.php
  tests/Model/EditableFormField/EditableFileFieldTest.php
  tests/Model/EditableFormField/EditableFormHeadingTest.php
  tests/Model/EditableFormField/EditableFormStepTest.php
  tests/Model/EditableFormField/EditableMemberListFieldTest.php
  tests/Model/EditableFormField/EditableMemberListFieldTest.yml
  tests/Model/EditableFormField/EditableNumericFieldTest.php
  tests/Model/EditableFormField/EditableRadioFieldTest.php
  tests/Model/EditableFormField/EditableTextFieldTest.php
  tests/Model/EditableFormFieldTest.php
Labels: affects/v4, change/patch

#752 FIX Use userforms template for member list field, fixes display rule issue
  code/model/editableformfields/EditableMemberListField.php
Labels: affects/v3, change/patch

#751 FIX Use a userforms template for the member list field, fixes broken display rules
  code/Model/EditableFormField/EditableMemberListField.php
Labels: affects/v4, change/patch

#749 FIX Ensure duplicated multiple option field is written (has an ID) before duplicating options
  code/Extension/UserFormFieldEditorExtension.php
  code/Model/EditableFormField/EditableMultipleOptionField.php
  tests/Model/EditableFormField/EditableDropdownTest.php
  tests/Model/UserDefinedFormTest.php
  tests/UserFormsTest.yml
Labels: affects/v4, change/patch

#755 FIX use the same translation variable key as core
  code/Model/EditableFormField.php
  lang/en.yml
Labels: affects/v4, change/patch, effort/easy, impact/high, type/bug
