Repository silverstripe/silverstripe-userforms, pull requests merged in 2019-03, with the labels that each got.

#866 BUGFIX: re-added can* methods for EditableOption field
  code/Model/EditableFormField/EditableOption.php
Labels: affects/v4, change/patch

#867 FIX Upgrade javascript dependencies and add babel-loader to ensure yarn build works
  client/dist/js/userforms-cms.js
  client/dist/js/userforms.js
  package.json
  yarn.lock
Labels: affects/v4, change/patch

#869 FIX correct userform reference & avoid submit errors
  client/dist/js/userforms.js
  client/src/bundles/UserForms.js
Labels: affects/v4, change/patch, feedback-required/author

#870 FIX Display rules for page breaks/editable form steps now works again
  code/Control/UserDefinedFormController.php
  code/Model/EditableCustomRule.php
  code/Model/EditableFormField.php
  tests/Model/EditableCustomRuleTest.php
Labels: affects/v4, change/patch

#872 FIX Display rules for page breaks/editable form steps now works again
  .travis.yml
  code/model/EditableCustomRule.php
  code/model/UserDefinedForm.php
  code/model/editableformfields/EditableFormField.php
  tests/EditableCustomRuleTest.php
Labels: affects/v3, change/patch

#871 Fix exception error message fails when error in upload file.
  code/Control/UserDefinedFormController.php
Labels: affects/v4, change/patch
